"""add_initial_capital_and_current_amount_to_portfolio

Revision ID: 0b5d5eadff78
Revises: 4b93424c3a97
Create Date: 2026-01-10 23:54:09.020099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b5d5eadff78'
down_revision: Union[str, Sequence[str], None] = '4b93424c3a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_assets', sa.Column('current_amount', sa.Float(), nullable=True))
    op.add_column('portfolios', sa.Column('initial_capital', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'initial_capital')
    op.drop_column('portfolio_assets', 'current_amount')
    # ### end Alembic commands ###
