"""Add interval to Asset model

Revision ID: 2ef3cef95c34
Revises: bd8726c544dd
Create Date: 2025-12-29 18:18:04.332808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef3cef95c34'
down_revision: Union[str, Sequence[str], None] = 'bd8726c544dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('interval', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'interval')
    # ### end Alembic commands ###
