"""add_is_favorite_to_portfolio

Revision ID: 4b93424c3a97
Revises: 59e5c3915bee
Create Date: 2026-01-10 23:02:48.096185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b93424c3a97'
down_revision: Union[str, Sequence[str], None] = '59e5c3915bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'is_favorite')
    # ### end Alembic commands ###
