"""add_portfolio_models

Revision ID: 59e5c3915bee
Revises: 671af61843b7
Create Date: 2026-01-10 22:38:46.029190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e5c3915bee'
down_revision: Union[str, Sequence[str], None] = '671af61843b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_table('portfolio_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_assets_id'), 'portfolio_assets', ['id'], unique=False)
    op.add_column('simulations', sa.Column('portfolio_id', sa.Integer(), nullable=True))
    op.alter_column('simulations', 'asset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'simulations', 'portfolios', ['portfolio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'simulations', type_='foreignkey')
    op.alter_column('simulations', 'asset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('simulations', 'portfolio_id')
    op.drop_index(op.f('ix_portfolio_assets_id'), table_name='portfolio_assets')
    op.drop_table('portfolio_assets')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
