"""add_is_favorite_to_simulation

Revision ID: 671af61843b7
Revises: a1bdfc4d3cc0
Create Date: 2026-01-10 16:58:00.163982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671af61843b7'
down_revision: Union[str, Sequence[str], None] = 'a1bdfc4d3cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'is_favorite')
    # ### end Alembic commands ###
