"""Add smart features to simulation model

Revision ID: 6872c7affde3
Revises: bd65290b61c5
Create Date: 2026-01-05 21:35:15.500341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6872c7affde3'
down_revision: Union[str, Sequence[str], None] = 'bd65290b61c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('dynamic_timing_enabled', sa.Boolean(), nullable=True))
    op.add_column('simulations', sa.Column('timing_aggressiveness', sa.Float(), nullable=True))
    op.add_column('simulations', sa.Column('dynamic_sizing_enabled', sa.Boolean(), nullable=True))
    op.add_column('simulations', sa.Column('sizing_multiplier', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'sizing_multiplier')
    op.drop_column('simulations', 'dynamic_sizing_enabled')
    op.drop_column('simulations', 'timing_aggressiveness')
    op.drop_column('simulations', 'dynamic_timing_enabled')
    # ### end Alembic commands ###
