"""add_rebalancing_fields

Revision ID: 6997e874131b
Revises: 4708ca55c6fe
Create Date: 2026-01-19 20:01:10.777965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6997e874131b'
down_revision: Union[str, Sequence[str], None] = '4708ca55c6fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('rebalancing_enabled', sa.Boolean(), nullable=True))
    op.add_column('simulations', sa.Column('periodic_rebalancing_enabled', sa.Boolean(), nullable=True))
    op.add_column('simulations', sa.Column('periodic_rebalancing_interval', sa.Integer(), nullable=True))
    op.add_column('simulations', sa.Column('constant_rebalancing_enabled', sa.Boolean(), nullable=True))
    op.add_column('simulations', sa.Column('constant_rebalancing_metric', sa.String(length=20), nullable=True))
    op.drop_column('simulations', 'rebalancing_mode')
    op.drop_column('simulations', 'rebalancing_interval_months')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('rebalancing_interval_months', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('simulations', sa.Column('rebalancing_mode', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('simulations', 'constant_rebalancing_metric')
    op.drop_column('simulations', 'constant_rebalancing_enabled')
    op.drop_column('simulations', 'periodic_rebalancing_interval')
    op.drop_column('simulations', 'periodic_rebalancing_enabled')
    op.drop_column('simulations', 'rebalancing_enabled')
    # ### end Alembic commands ###
