"""add_portfolio_simulation_fields

Revision ID: 69c97b863fda
Revises: 0b5d5eadff78
Create Date: 2026-01-11 00:34:36.585134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c97b863fda'
down_revision: Union[str, Sequence[str], None] = '0b5d5eadff78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_results', sa.Column('asset_results', sa.Text(), nullable=True))
    op.add_column('simulations', sa.Column('rebalancing_mode', sa.String(length=20), nullable=True))
    op.add_column('simulations', sa.Column('rebalancing_interval_months', sa.Integer(), nullable=True))
    op.add_column('simulations', sa.Column('asset_configs', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'asset_configs')
    op.drop_column('simulations', 'rebalancing_interval_months')
    op.drop_column('simulations', 'rebalancing_mode')
    op.drop_column('simulation_results', 'asset_results')
    # ### end Alembic commands ###
