"""add_smart_dca_indicator_params

Revision ID: 8621745babec
Revises: 6877933248bd
Create Date: 2026-01-09 18:28:56.019598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8621745babec'
down_revision: Union[str, Sequence[str], None] = '6877933248bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('smart_indicator', sa.String(length=20), nullable=True))
    op.add_column('simulations', sa.Column('rsi_threshold_low', sa.Float(), nullable=True))
    op.add_column('simulations', sa.Column('rsi_threshold_high', sa.Float(), nullable=True))
    op.add_column('simulations', sa.Column('ma_period_short', sa.Integer(), nullable=True))
    op.add_column('simulations', sa.Column('ma_period_long', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'ma_period_long')
    op.drop_column('simulations', 'ma_period_short')
    op.drop_column('simulations', 'rsi_threshold_high')
    op.drop_column('simulations', 'rsi_threshold_low')
    op.drop_column('simulations', 'smart_indicator')
    # ### end Alembic commands ###
