"""remove_constant_rebalancing

Revision ID: 8cfe2b1b3462
Revises: 6997e874131b
Create Date: 2026-01-26 19:14:18.852821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cfe2b1b3462'
down_revision: Union[str, Sequence[str], None] = '6997e874131b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'constant_rebalancing_enabled')
    op.drop_column('simulations', 'periodic_rebalancing_enabled')
    op.drop_column('simulations', 'constant_rebalancing_metric')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('constant_rebalancing_metric', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('simulations', sa.Column('periodic_rebalancing_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('simulations', sa.Column('constant_rebalancing_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
