"""add_initial_capital

Revision ID: 9b3fa1945f5f
Revises: e18fce408966
Create Date: 2026-01-07 18:16:18.742360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3fa1945f5f'
down_revision: Union[str, Sequence[str], None] = 'e18fce408966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('initial_capital', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'initial_capital')
    # ### end Alembic commands ###
