"""add_expensive_buy_ratio

Revision ID: a1bdfc4d3cc0
Revises: 8621745babec
Create Date: 2026-01-10 16:31:51.059962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1bdfc4d3cc0'
down_revision: Union[str, Sequence[str], None] = '8621745babec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('expensive_buy_ratio', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'expensive_buy_ratio')
    # ### end Alembic commands ###
