"""add_investment_mode_and_fees

Revision ID: e18fce408966
Revises: 6872c7affde3
Create Date: 2026-01-07 18:11:44.018554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18fce408966'
down_revision: Union[str, Sequence[str], None] = '6872c7affde3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('investment_mode', sa.String(length=20), nullable=True))
    op.add_column('simulations', sa.Column('minimum_fee_per_trade', sa.Float(), nullable=True))
    op.add_column('simulations', sa.Column('maintenance_fee_annual_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'maintenance_fee_annual_percent')
    op.drop_column('simulations', 'minimum_fee_per_trade')
    op.drop_column('simulations', 'investment_mode')
    # ### end Alembic commands ###
